services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: SummerBornInfo.Web/Dockerfile
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
      - POSTGRES_DB=summerborn_info
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d summerborn_info -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  adminer:
    image: shyim/adminerevo:4.8.4
    restart: always
    ports:
      - 8080:8080
volumes:
  db:
    driver: local