global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Npgmq;
global using SummerBornInfo.AppHost.ServiceDefaults;
global using SummerBornInfo.Features.Schools.Commands.Import;
global using SummerBornInfo.Features.Schools.Queries.GetAllSchools;
global using SummerBornInfo.Infrastructure.Events;
global using SummerBornInfo.Infrastructure.Persistence;
global using SummerBornInfo.Web.API.Schools;
