-- Bootstraps the first admin identity for the Milestone 2 ASP.NET Core Identity schema.
-- Run with psql and supply a precomputed ASP.NET Core Identity password hash, for example:
-- psql "$DATABASE_URL" -v admin_email='admin@example.com' -v admin_password_hash='AQAAAAIAAYagAAAA...' -f ProductionScripts/bootstrap-initial-admin.sql
--
-- Required psql variables:
--   admin_email
--   admin_password_hash
--
-- Optional psql variables:
--   admin_role_name (defaults to Admin)
--
-- Notes:
-- - This script targets the current PostgreSQL Identity tables in the public schema:
--   application_user, application_role, application_user_role.
-- - The password hash must be generated by trusted application code or another trusted .NET environment.
--   This script does not attempt to invent a password or hash in SQL.
-- - Re-running the script is safe: it creates missing rows, normalizes key fields, and ensures the role assignment exists.
--   It does not overwrite an existing non-null PasswordHash for a matched user.

\set ON_ERROR_STOP on

\if :{?admin_email}
\else
\echo 'Missing required psql variable: admin_email'
\quit 3
\endif

\if :{?admin_password_hash}
\else
\echo 'Missing required psql variable: admin_password_hash'
\quit 3
\endif

\if :{?admin_role_name}
\else
\set admin_role_name Admin
\endif

BEGIN;

DO $bootstrap$
DECLARE
    normalized_admin_email text := upper(:'admin_email');
    matching_user_count integer;
BEGIN
    IF to_regclass('public.application_user') IS NULL THEN
        RAISE EXCEPTION 'Required table public.application_user does not exist. Apply the Milestone 2 identity schema before running this script.';
    END IF;

    IF to_regclass('public.application_role') IS NULL THEN
        RAISE EXCEPTION 'Required table public.application_role does not exist. Apply the Milestone 2 identity schema before running this script.';
    END IF;

    IF to_regclass('public.application_user_role') IS NULL THEN
        RAISE EXCEPTION 'Required table public.application_user_role does not exist. Apply the Milestone 2 identity schema before running this script.';
    END IF;

    SELECT count(*)
    INTO matching_user_count
    FROM public.application_user
    WHERE "NormalizedEmail" = normalized_admin_email
       OR "NormalizedUserName" = normalized_admin_email;

    IF matching_user_count > 1 THEN
        RAISE EXCEPTION
            'More than one application_user row already matches admin email % by normalized email or username. Resolve that ambiguity manually before re-running this script.',
            :'admin_email';
    END IF;
END
$bootstrap$;

WITH role_input AS
(
    SELECT
        :'admin_role_name'::text AS role_name,
        upper(:'admin_role_name')::text AS normalized_role_name,
        (
            substr(md5('role:' || upper(:'admin_role_name')), 1, 8) || '-' ||
            substr(md5('role:' || upper(:'admin_role_name')), 9, 4) || '-' ||
            '4' || substr(md5('role:' || upper(:'admin_role_name')), 14, 3) || '-' ||
            'a' || substr(md5('role:' || upper(:'admin_role_name')), 18, 3) || '-' ||
            substr(md5('role:' || upper(:'admin_role_name')), 21, 12)
        )::uuid AS generated_role_id,
        md5('role-concurrency-stamp:' || upper(:'admin_role_name')) AS generated_role_concurrency_stamp
)
INSERT INTO public.application_role
(
    "Id",
    "Name",
    "NormalizedName",
    "ConcurrencyStamp"
)
SELECT
    role_input.generated_role_id,
    role_input.role_name,
    role_input.normalized_role_name,
    role_input.generated_role_concurrency_stamp
FROM role_input
WHERE NOT EXISTS
(
    SELECT 1
    FROM public.application_role role_row
    WHERE role_row."NormalizedName" = role_input.normalized_role_name
);

WITH role_input AS
(
    SELECT
        :'admin_role_name'::text AS role_name,
        upper(:'admin_role_name')::text AS normalized_role_name
)
UPDATE public.application_role role_row
SET
    "Name" = role_input.role_name,
    "NormalizedName" = role_input.normalized_role_name
FROM role_input
WHERE role_row."NormalizedName" = role_input.normalized_role_name
  AND
  (
      role_row."Name" IS DISTINCT FROM role_input.role_name
      OR role_row."NormalizedName" IS DISTINCT FROM role_input.normalized_role_name
  );

WITH user_input AS
(
    SELECT
        :'admin_email'::text AS admin_email,
        upper(:'admin_email')::text AS normalized_admin_email,
        :'admin_password_hash'::text AS admin_password_hash,
        (
            substr(md5('user:' || upper(:'admin_email')), 1, 8) || '-' ||
            substr(md5('user:' || upper(:'admin_email')), 9, 4) || '-' ||
            '4' || substr(md5('user:' || upper(:'admin_email')), 14, 3) || '-' ||
            'a' || substr(md5('user:' || upper(:'admin_email')), 18, 3) || '-' ||
            substr(md5('user:' || upper(:'admin_email')), 21, 12)
        )::uuid AS generated_user_id,
        md5('user-security-stamp:' || upper(:'admin_email') || ':' || :'admin_password_hash') AS generated_security_stamp,
        md5('user-concurrency-stamp:' || upper(:'admin_email')) AS generated_user_concurrency_stamp
)
INSERT INTO public.application_user
(
    "Id",
    "UserName",
    "NormalizedUserName",
    "Email",
    "NormalizedEmail",
    "EmailConfirmed",
    "PasswordHash",
    "SecurityStamp",
    "ConcurrencyStamp",
    "PhoneNumber",
    "PhoneNumberConfirmed",
    "TwoFactorEnabled",
    "LockoutEnd",
    "LockoutEnabled",
    "AccessFailedCount"
)
SELECT
    user_input.generated_user_id,
    user_input.admin_email,
    user_input.normalized_admin_email,
    user_input.admin_email,
    user_input.normalized_admin_email,
    TRUE,
    user_input.admin_password_hash,
    user_input.generated_security_stamp,
    user_input.generated_user_concurrency_stamp,
    NULL,
    FALSE,
    FALSE,
    NULL,
    FALSE,
    0
FROM user_input
WHERE NOT EXISTS
(
    SELECT 1
    FROM public.application_user user_row
    WHERE user_row."NormalizedEmail" = user_input.normalized_admin_email
       OR user_row."NormalizedUserName" = user_input.normalized_admin_email
);

WITH user_input AS
(
    SELECT
        :'admin_email'::text AS admin_email,
        upper(:'admin_email')::text AS normalized_admin_email,
        :'admin_password_hash'::text AS admin_password_hash,
        md5('user-security-stamp:' || upper(:'admin_email') || ':' || :'admin_password_hash') AS generated_security_stamp,
        md5('user-concurrency-stamp:' || upper(:'admin_email')) AS generated_user_concurrency_stamp
)
UPDATE public.application_user user_row
SET
    "UserName" = user_input.admin_email,
    "NormalizedUserName" = user_input.normalized_admin_email,
    "Email" = user_input.admin_email,
    "NormalizedEmail" = user_input.normalized_admin_email,
    "EmailConfirmed" = TRUE,
    "PasswordHash" = CASE
        WHEN user_row."PasswordHash" IS NULL THEN user_input.admin_password_hash
        ELSE user_row."PasswordHash"
    END,
    "SecurityStamp" = CASE
        WHEN user_row."SecurityStamp" IS NULL THEN user_input.generated_security_stamp
        ELSE user_row."SecurityStamp"
    END,
    "ConcurrencyStamp" = COALESCE(user_row."ConcurrencyStamp", user_input.generated_user_concurrency_stamp)
FROM user_input
WHERE
    (
        user_row."NormalizedEmail" = user_input.normalized_admin_email
        OR user_row."NormalizedUserName" = user_input.normalized_admin_email
    )
    AND
    (
        user_row."UserName" IS DISTINCT FROM user_input.admin_email
        OR user_row."NormalizedUserName" IS DISTINCT FROM user_input.normalized_admin_email
        OR user_row."Email" IS DISTINCT FROM user_input.admin_email
        OR user_row."NormalizedEmail" IS DISTINCT FROM user_input.normalized_admin_email
        OR user_row."EmailConfirmed" IS DISTINCT FROM TRUE
        OR user_row."PasswordHash" IS NULL
        OR user_row."SecurityStamp" IS NULL
        OR user_row."ConcurrencyStamp" IS NULL
    );

INSERT INTO public.application_user_role
(
    "UserId",
    "RoleId"
)
SELECT
    user_row."Id",
    role_row."Id"
FROM public.application_user user_row
JOIN public.application_role role_row
    ON role_row."NormalizedName" = upper(:'admin_role_name')
WHERE
    (
        user_row."NormalizedEmail" = upper(:'admin_email')
        OR user_row."NormalizedUserName" = upper(:'admin_email')
    )
    AND NOT EXISTS
    (
        SELECT 1
        FROM public.application_user_role user_role_row
        WHERE user_role_row."UserId" = user_row."Id"
          AND user_role_row."RoleId" = role_row."Id"
    );

SELECT
    user_row."Id" AS admin_user_id,
    user_row."Email" AS admin_email,
    role_row."Id" AS admin_role_id,
    role_row."Name" AS admin_role_name,
    user_row."PasswordHash" = :'admin_password_hash' AS password_hash_matches_supplied_value,
    EXISTS
    (
        SELECT 1
        FROM public.application_user_role user_role_row
        WHERE user_role_row."UserId" = user_row."Id"
          AND user_role_row."RoleId" = role_row."Id"
    ) AS admin_role_assigned
FROM public.application_user user_row
JOIN public.application_role role_row
    ON role_row."NormalizedName" = upper(:'admin_role_name')
WHERE
    user_row."NormalizedEmail" = upper(:'admin_email')
    OR user_row."NormalizedUserName" = upper(:'admin_email');

COMMIT;
